### PR TITLE
Truncate the issue's title to 254 chars

### PR DESCRIPTION
**Pull request by qgong**
The JIRA issue summary can not be more than 254 chars, otherwise it will throw error:
http://pastebin.test.redhat.com/960490

### CODE REVIEW

**Comment by qgong** [comment]
@ralphbean please help review this PR, thank you.

**Comment by qgong** [comment]
https://github.com/release-engineering/Sync2Jira/issues/120

**Review by sidpremkumar — APPROVED** [review]

**Comment by qgong** [comment]
@mnecas Ok let me ask help from ralph directly.

**Comment by ralphbean** [comment]
Ack - LGTM. Thanks for the ping! Sorry for the delay.

**Pull request merged**
