### PR TITLE
Use GitHub Actions instead of Travis CI

### PR DESCRIPTION
**Pull request by hluk**

### CODE REVIEW

**Comment by hluk** [comment]
Not sure why it doesn't work here.

Tested here: https://github.com/hluk/Sync2Jira/pull/1

**Comment by ralphbean** [comment]
Weird, I don't see it either.

On this branch, `tox` works locally for me.

I tried re-running the action, but it failed again.

**Comment by hluk** [comment]
Oh, I just pushed the original branch with `.github/*` to this upstream repo (`github-actions` branch) and the new tests finally run!

**Review by sidpremkumar — APPROVED** [review]
+1

**Comment by hluk** [comment]
@sidpremkumar Is it OK to merge this? Not sure if I'm allowed to do this. Is there a guide for contributors/developers?

**Comment by sidpremkumar** [comment]
Just took a look. Looks good to me, but I'm no longer the main dev for this project. I believe @ralphbean should know , I would ask them.

**Comment by ralphbean** [comment]
Can do!

**Pull request merged**
