### PR TITLE
Add issue links to pr

### PR DESCRIPTION
**Pull request by sidpremkumar**
~~Testing on Stage prior to master~~
Tested on Stage and everything went as expected. 
From the original issue:

> It would be cool when we link a PR we add the PR URL to issue_links on JIRA
> Taking this Issue. also we need to check against issue_links, instead of just looking for a matching comment. I noticed that sometimes we could double comment when a user would remove the WIP title.

### CODE REVIEW

**Comment by sidpremkumar** [comment]
@gabdzo PTAL as well , thanks

**Comment by sidpremkumar** [comment]
Relates to JIRA: PVDRASP-554

**Comment by ralphbean** [comment]
I'll leave this one to @gabdzo.  :)

**Comment by gabdzo** [comment]
+1

**Pull request merged**
